# Generated by Django 5.0.1 on 2024-01-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercemain', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type_name', models.CharField(blank=True, max_length=45, null=True)),
                ('max_product_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommercemain.status')),
            ],
        ),
    ]
